### PR TITLE
Some functions

### PR DESCRIPTION
**Pull request by delanoe**
I have added some maybes in Transaction Type (needed for my tests)
Maybe you do not need them, tell me. I can remove it.

### CODE REVIEW

**Comment by delanoe** [comment]
0 examples, 0 failures

Why only caml case since with _ I find it easier to read (and it compiles of course) ?

**Comment by jdreaver** [comment]
> 0 examples, 0 failures

Heh, yeah I've just been testing this locally. I didn't want to deal with the headache of making fake OANDA credentials just for integration tests, dealing with flaky CI tests because of network errors or rate limits, and also dealing with keeping those test credentials secret in CI.

> Why only caml case since with _ I find it easier to read (and it compiles of course) ?

I just find camelCase more consistently used in the Haskell community. What's more important than any particular style choice is just having a consistent style.

By the way thanks for the PR! I'm extremely busy this week but I have reviewing this PR on my todo list.

**Comment by delanoe** [comment]
Ok, I understand. I have just pushed a fix. Then all checks should be ok now.

**Comment by delanoe** [comment]
Hello,
"flaky CI tests because of network errors or rate limits" You mean you get these errors:

InternalException (HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,HandshakeFailure)]" " expected: change cipher"

I do not know how to deal with it.

**Comment by jdreaver** [comment]
Hah, I actually encountered that in production a couple months ago and never files an issue. I simply catch the exception, ignore it, and retry the function.

> flaky CI tests because of network errors or rate limits

I wasn't referring to this error specifically, but to flaky tests in general. The only real way to test this library is by talking to OANDA directly. This poses a problem because we will inevitably get network errors that we have to investigate, and also OANDA will only return the correct responses for some endpoints during certain times on weekdays. I just don't want to deal with the headache of maintaining the test suite.

**Pull request closed without merging**
